# -*- coding: utf-8 -*-
"""ML_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BlqAuXZ7LafF48KzPU6MBKkmoWGd_y2g

1. Data Collection
"""

import numpy as np
from sklearn.datasets import fetch_openml

# Load MNIST dataset
mnist = fetch_openml('mnist_784', version=1)
X, y = mnist["data"], mnist["target"]

"""2. Data Precprocessing"""

from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""3. Model Building"""

from sklearn.svm import SVC

# Initialize SVM classifier
svm_clf = SVC(kernel='rbf', C=10, gamma='scale')

"""4. Model Training"""

# Train the SVM model
svm_clf.fit(X_train, y_train)

"""5. Model Evaluation"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Predictions on test set
y_pred = svm_clf.predict(X_test)

# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

"""6. Model Deployment"""

